name = "LearnLooper"
uuid = "e89896d8-c5cb-49c4-9dca-99a75ba5130e"
authors = ["hannahilea <hannahilea@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Sound = "afe32e48-2646-410f-a1df-ae97debbc86b"
TimeSpans = "bb34ddd2-327f-4c4a-bfb0-c98fc494ece1"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
Aqua = "0.6"
Sound = "0.5.0"
TimeSpans = "1.1.0"
WAV = "1.2.0"
julia = "1.7.2"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
