name: LearnLooper.jl - Docs
on:
  workflow_dispatch:
  push:
    tags: ['*']
    branches:
      - main
    paths:
      - '.github/workflows/LearnLooper_docs.yml'
      - 'LearnLooper.jl/docs/**'
      - 'LearnLooper.jl/src/**'
      - 'LearnLooper.jl/Project.toml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/LearnLooper_docs.yml'
      - 'LearnLooper.jl/docs/**'
      - 'LearnLooper.jl/src/**'
      - 'LearnLooper.jl/Project.toml'
jobs:
  Documentation:
    # Run on push's or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.7
      - name: Install dependencies
        run: |
          julia --project=docs/ -e 'using Pkg;
              Pkg.instantiate()
              Pkg.develop(PackageSpec(path=pwd()));
              Pkg.instantiate()'
        working-directory: LearnLooper.jl
      - run: julia --project=docs "docs/make.jl"
        working-directory: LearnLooper.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          PYTHON: ""
